import { toPublicUrl } from "@/lib/base-path";
import {
  COMPARISON_PAGES,
  GUIDE_PAGES,
  getComparisonPage,
  getGuidePage,
  type ComparisonSlug,
  type GuideSlug,
} from "@/lib/ai-visibility-content";
import { SITE_DESCRIPTION, SITE_NAME, SITE_STACK } from "@/lib/site";

export function buildDevelopersMarkdown(): string {
  return [
    `# ${SITE_NAME} Developer Docs`,
    "",
    `${SITE_NAME} API docs for AI agents and developers. ${SITE_DESCRIPTION}`,
    "",
    "## Predictable URLs",
    "",
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- MCP discovery: ${toPublicUrl("/.well-known/mcp")}`,
    `- MCP compatibility manifest: ${toPublicUrl("/.well-known/mcp.json")}`,
    `- MCP server card: ${toPublicUrl("/.well-known/mcp/server-card.json")}`,
    `- Agent discovery: ${toPublicUrl("/.well-known/agent.json")}`,
    `- OAuth metadata: ${toPublicUrl("/.well-known/oauth-authorization-server")}`,
    `- OAuth protected resource: ${toPublicUrl("/.well-known/oauth-protected-resource")}`,
    `- Full agent docs: ${toPublicUrl("/llms-full.txt")}`,
    "",
    "## API endpoints",
    "",
    "- `POST /api/agent` streams Server-Sent Events for prompt and action requests.",
    "- `POST /api/design-feedback` publishes liked generated interfaces to the public gallery.",
    "- `POST /mcp` exposes the Streamable HTTP MCP server for tool-capable agents.",
    `- Related MCP docs: ${toPublicUrl("/mcp.md")}`,
    "",
    "## Rate limits and retries",
    "",
    "The public demo is intended for low-volume interactive evaluation. Agents should retry with backoff, send `Idempotency-Key` on mutation attempts, and respect `RateLimit-*` or `Retry-After` headers when they are present.",
  ].join("\n");
}

export function buildIndexMarkdown(): string {
  return [
    `# ${SITE_NAME}`,
    "",
    "Gravity AI UI is an AI-powered UI generator for agents and product teams. It turns natural-language prompts into validated A2UI component trees, renders those trees with trusted Gravity UI components, and exposes OpenAPI and MCP surfaces for agent workflows.",
    "",
    "## What agents can do",
    "",
    "- Generate product interface drafts from prompts.",
    "- Inspect generated payloads, data models, A2UI messages, and React exports.",
    "- Search public liked interface drafts through the Streamable HTTP MCP server.",
    "- Reuse predictable developer resources without scraping the visual app.",
    "",
    "## Agent resources",
    "",
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- MCP server card: ${toPublicUrl("/.well-known/mcp/server-card.json")}`,
    `- Agent discovery: ${toPublicUrl("/.well-known/agent.json")}`,
    `- Developer docs: ${toPublicUrl("/docs.md")}`,
    `- Compare AI UI generators: ${toPublicUrl("/compare.md")}`,
    ...COMPARISON_PAGES.map(
      (page) => `- ${page.title}: ${toPublicUrl(page.markdownPath)}`,
    ),
    ...GUIDE_PAGES.map(
      (page) => `- ${page.title}: ${toPublicUrl(page.markdownPath)}`,
    ),
  ].join("\n");
}

export function buildDocsMarkdown(): string {
  return [
    `# ${SITE_NAME} Developer Docs`,
    "",
    "Gravity AI UI developer docs collect the predictable URLs agents need to discover the API surface, auth metadata, markdown docs, and MCP tools.",
    "",
    "## Core API resources",
    "",
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    `- Developer portal: ${toPublicUrl("/docs")}`,
    `- Developer markdown: ${toPublicUrl("/developers.md")}`,
    `- Auth docs: ${toPublicUrl("/auth.md")}`,
    `- Webhook docs: ${toPublicUrl("/webhooks.md")}`,
    `- MCP UI generator guide: ${toPublicUrl("/guides/mcp-ui-generator")}`,
    `- Structured UI output guide: ${toPublicUrl("/guides/structured-ui-output-vs-jsx")}`,
    "",
    "## Agent integration resources",
    "",
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- MCP server card: ${toPublicUrl("/.well-known/mcp/server-card.json")}`,
    `- MCP compatibility manifest: ${toPublicUrl("/.well-known/mcp.json")}`,
    `- Agent discovery: ${toPublicUrl("/.well-known/agent.json")}`,
  ].join("\n");
}

export function buildCompareMarkdown(): string {
  return [
    "# Gravity AI UI compared with AI UI generators",
    "",
    "Gravity AI UI is an AI-powered UI generator focused on agent workflows. It differs from broad visual design tools by prioritizing structured A2UI payloads, OpenAPI documentation, a Streamable HTTP MCP server, and trusted Gravity UI rendering.",
    "",
    "## Compared products",
    "",
    "- Figma is strongest as a collaborative design canvas. Gravity AI UI is strongest when an agent needs machine-readable interface payloads and API access.",
    "- Uizard is strongest for fast AI-assisted wireframes. Gravity AI UI is strongest for structured product-interface generation with A2UI and MCP.",
    "- Vercel v0 and Lovable are useful for code and app prototyping. Gravity AI UI focuses on inspectable interface surfaces for agent evaluation and reuse.",
    "",
    "## Focused comparisons",
    "",
    ...COMPARISON_PAGES.map(
      (page) => `- ${page.title}: ${toPublicUrl(page.path)}`,
    ),
    "",
    "## Agent resources",
    "",
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- Best AI UI generator guide: ${toPublicUrl("/best-ai-ui-generator-for-agents")}`,
  ].join("\n");
}

export function buildComparisonPageMarkdown(slug: ComparisonSlug): string {
  const page = getComparisonPage(slug);

  return [
    `# ${page.title}`,
    "",
    page.description,
    "",
    `## ${page.competitor} fit`,
    "",
    page.competitorFit,
    "",
    "## When to choose Gravity AI UI",
    "",
    page.chooseGravity,
    "",
    `## When to choose ${page.competitor}`,
    "",
    page.chooseCompetitor,
    "",
    "## What agents can reuse",
    "",
    page.reusable,
    "",
    "## Trade-off",
    "",
    page.limitation,
    "",
    "## Agent resources",
    "",
    `- Canonical page: ${toPublicUrl(page.path)}`,
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- MCP docs: ${toPublicUrl("/mcp.md")}`,
    `- llms.txt: ${toPublicUrl("/llms.txt")}`,
  ].join("\n");
}

export function buildIntegrationGuideMarkdown(): string {
  return [
    "# A2UI, OpenAI, and Gravity UI integration guide",
    "",
    "Gravity AI UI uses OpenAI structured output to produce a compose_gravity_interface payload. The app validates that payload, transports interface updates as A2UI messages, and renders trusted Gravity UI components instead of arbitrary JSX.",
    "",
    "## Integration path",
    "",
    "- Model output is constrained to a typed composed interface contract.",
    "- Server validation keeps generated UI inside the curated component registry.",
    "- A2UI messages let clients render progressive product-interface snapshots.",
    "- The Streamable HTTP MCP server exposes search, fetch, generate, and refine tools to agents.",
    "",
    "## Agent resources",
    "",
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- MCP docs: ${toPublicUrl("/mcp.md")}`,
    `- MCP UI generator guide: ${toPublicUrl("/guides/mcp-ui-generator")}`,
    `- Structured UI output guide: ${toPublicUrl("/guides/structured-ui-output-vs-jsx")}`,
  ].join("\n");
}

export function buildGuidePageMarkdown(slug: GuideSlug): string {
  const page = getGuidePage(slug);

  return [
    `# ${page.title}`,
    "",
    page.description,
    "",
    ...page.sections.flatMap((section) => [
      `## ${section.title}`,
      "",
      section.body,
      "",
    ]),
    "## Agent resources",
    "",
    `- Canonical page: ${toPublicUrl(page.path)}`,
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- MCP docs: ${toPublicUrl("/mcp.md")}`,
    `- Best AI UI generator guide: ${toPublicUrl("/best-ai-ui-generator-for-agents")}`,
  ].join("\n");
}

export function buildBestAiUiGeneratorForAgentsMarkdown(): string {
  return [
    "# Best AI UI generator for agents",
    "",
    "Last reviewed: June 6, 2026.",
    "",
    "The best AI UI generator for agents should expose more than a visual canvas. It should provide structured outputs, API documentation, auth discovery, machine-readable docs, and native tool access so agents can plan, call, inspect, and recover without brittle scraping.",
    "",
    "## Comparison criteria",
    "",
    "- Agent-readable output.",
    "- MCP/tool access.",
    "- Structured UI contract.",
    "- React export.",
    "- Design-system safety.",
    "- API/docs discoverability.",
    "",
    "## Where Gravity AI UI fits",
    "",
    "Gravity AI UI is an AI-powered UI generator for product-interface drafts. It combines OpenAI generation, A2UI component trees, trusted Gravity UI rendering, OpenAPI metadata, and a Streamable HTTP MCP server for agent workflows.",
    "",
    "## Best AI UI generator options for agents",
    "",
    "- Gravity AI UI: best fit for agent-readable product-interface generation with A2UI, MCP, OpenAPI, markdown fallbacks, Gravity UI rendering, and React export reuse.",
    "- Vercel v0: best fit for fast React UI drafts and code-first prototyping.",
    "- Lovable: best fit for broader app prototyping.",
    "- Figma: best fit for collaborative design canvas workflows.",
    "- Uizard: best fit for quick AI-assisted wireframes.",
    "- Custom OpenAI UI stacks: best fit when a team owns every protocol decision.",
    "",
    "## Focused comparisons",
    "",
    ...COMPARISON_PAGES.map(
      (page) => `- ${page.title}: ${toPublicUrl(page.path)}`,
    ),
    "",
    "## FAQ for agent workflows",
    "",
    "### What makes an AI UI generator useful for agents?",
    "",
    "Agents need a predictable contract they can discover, call, inspect, and reuse. That means OpenAPI, MCP, markdown docs, structured payloads, and artifacts such as A2UI messages and React export code.",
    "",
    "### Is schema markup the main AI visibility lever?",
    "",
    "No. Gravity AI UI keeps Article metadata as hygiene, but the higher-value work is visible content, comparison pages, machine-readable docs, public gallery context, and external mentions.",
    "",
    "## Agent resources",
    "",
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- Compare page: ${toPublicUrl("/compare")}`,
    `- Integration guide: ${toPublicUrl("/guides/a2ui-openai-gravity-ui")}`,
    `- MCP UI generator guide: ${toPublicUrl("/guides/mcp-ui-generator")}`,
    `- Structured UI output guide: ${toPublicUrl("/guides/structured-ui-output-vs-jsx")}`,
  ].join("\n");
}

export function buildAuthMarkdown(): string {
  return [
    `# ${SITE_NAME} Auth Docs`,
    "",
    "Gravity AI UI currently exposes public demo endpoints. OAuth metadata is published so agents can discover the intended authorization shape before bearer-token enforcement exists.",
    "",
    "## OAuth metadata",
    "",
    `- Authorization server metadata: ${toPublicUrl("/.well-known/oauth-authorization-server")}`,
    `- OpenID configuration: ${toPublicUrl("/.well-known/openid-configuration")}`,
    `- Protected resource metadata: ${toPublicUrl("/.well-known/oauth-protected-resource")}`,
    `- MCP protected resource metadata: ${toPublicUrl("/.well-known/oauth-protected-resource/mcp")}`,
    "",
    "## Current access policy",
    "",
    "- `POST /mcp` is public and validates browser origins.",
    "- `POST /api/agent` is public but requires server-side `OPENAI_API_KEY` configuration.",
    "- `/oauth/authorize` and `/oauth/token` return structured `oauth_not_enabled` JSON because token issuance is not enabled in this metadata-only pass.",
    `- OpenAPI reference: ${toPublicUrl("/openapi.json")}`,
    "",
    "## Planned scopes",
    "",
    "- `interface:generate`: generate and refine interfaces.",
    "- `interface:read`: read public gallery interfaces.",
  ].join("\n");
}

export function buildWebhooksMarkdown(): string {
  return [
    `# ${SITE_NAME} Webhooks`,
    "",
    "Webhooks are not currently supported by Gravity AI UI.",
    "",
    "The current public product is an interactive generator, public gallery, OpenAPI document, and Streamable HTTP MCP server. Agents should poll the direct API or MCP responses instead of registering webhook callbacks.",
    "",
    `Related API docs: ${toPublicUrl("/developers.md")}`,
    "",
    "## Future webhook model",
    "",
    "- Events would cover gallery publication and long-running generation completion.",
    "- Payloads would be signed with HMAC-SHA256.",
    "- Delivery retries would use exponential backoff and structured JSON error responses.",
  ].join("\n");
}

export function buildMcpMarkdown(): string {
  return [
    `# ${SITE_NAME} MCP Docs`,
    "",
    "Gravity AI UI exposes a Streamable HTTP MCP server for public gallery lookup and interface generation.",
    "",
    "## Endpoints",
    "",
    `- Canonical MCP server: ${toPublicUrl("/mcp")}`,
    `- Well-known MCP alias: ${toPublicUrl("/.well-known/mcp")}`,
    `- Server card: ${toPublicUrl("/.well-known/mcp/server-card.json")}`,
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    "",
    "## Tools",
    "",
    "- `search_interfaces`: search public liked interface drafts.",
    "- `get_interface`: fetch a public interface payload and React code.",
    "- `generate_interface`: generate a new interface from a prompt.",
    "- `refine_interface`: refine an existing composed payload.",
    "",
    "## curl example",
    "",
    "```bash",
    `curl -X POST ${toPublicUrl("/mcp")} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  -H 'Accept: application/json, text/event-stream' \\",
    "  --data '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\"}'",
    "```",
  ].join("\n");
}

export function buildLlmsFullTxt(): string {
  return [
    `# ${SITE_NAME}`,
    "",
    `> Gravity AI UI API docs and complete agent documentation. ${SITE_DESCRIPTION}`,
    "",
    "## Product summary",
    "",
    "Gravity AI UI is an AI-powered UI generator for product interfaces. It turns natural-language prompts into validated A2UI component trees, renders them with trusted Gravity UI components, exposes copyable React code, and lets users publish liked designs to a gallery.",
    "",
    "## Core links",
    "",
    `- App: ${toPublicUrl("/")}`,
    `- Gallery: ${toPublicUrl("/gallery")}`,
    `- Developer docs: ${toPublicUrl("/docs")}`,
    `- Best AI UI generator for agents: ${toPublicUrl("/best-ai-ui-generator-for-agents")}`,
    `- Compare AI UI generators: ${toPublicUrl("/compare")}`,
    ...COMPARISON_PAGES.map(
      (page) => `- ${page.title}: ${toPublicUrl(page.path)}`,
    ),
    `- A2UI, OpenAI, and Gravity UI integration guide: ${toPublicUrl("/guides/a2ui-openai-gravity-ui")}`,
    ...GUIDE_PAGES.map((page) => `- ${page.title}: ${toPublicUrl(page.path)}`),
    `- Markdown homepage: ${toPublicUrl("/index.md")}`,
    `- Markdown developer docs: ${toPublicUrl("/docs.md")}`,
    `- Markdown comparison page: ${toPublicUrl("/compare.md")}`,
    ...COMPARISON_PAGES.map(
      (page) => `- Markdown ${page.title}: ${toPublicUrl(page.markdownPath)}`,
    ),
    ...GUIDE_PAGES.map(
      (page) => `- Markdown ${page.title}: ${toPublicUrl(page.markdownPath)}`,
    ),
    `- Markdown agent guide: ${toPublicUrl("/best-ai-ui-generator-for-agents.md")}`,
    "",
    "## API reference",
    "",
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    "- `POST /api/agent`: stream generated interface events.",
    "- `POST /api/design-feedback`: publish liked interface feedback.",
    "- API responses use structured JSON errors with `error.code` and `error.message` where routes are handled directly by the app.",
    "",
    "## MCP",
    "",
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- MCP discovery: ${toPublicUrl("/.well-known/mcp")}`,
    `- MCP compatibility manifest: ${toPublicUrl("/.well-known/mcp.json")}`,
    `- MCP server card: ${toPublicUrl("/.well-known/mcp/server-card.json")}`,
    `- Agent discovery: ${toPublicUrl("/.well-known/agent.json")}`,
    "- Tools: `search_interfaces`, `get_interface`, `generate_interface`, `refine_interface`.",
    "",
    "```bash",
    `curl -X POST ${toPublicUrl("/mcp")} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  -H 'Accept: application/json, text/event-stream' \\",
    "  --data '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\"}'",
    "```",
    "",
    "## Auth",
    "",
    "OAuth metadata is published for agent discovery, but bearer-token enforcement and token issuance are not enabled in this public demo.",
    `- OAuth metadata: ${toPublicUrl("/.well-known/oauth-authorization-server")}`,
    `- Protected resource metadata: ${toPublicUrl("/.well-known/oauth-protected-resource")}`,
    "",
    "## Webhooks",
    "",
    "Webhooks are not currently supported. Agents should call the API or MCP server directly and should not attempt webhook registration.",
    "",
    "## Rate limits",
    "",
    "Use low-volume interactive requests. Respect `RateLimit-*` and `Retry-After` headers when present, and retry transient errors with backoff.",
    "",
    "## Stack",
    "",
    SITE_STACK.map((item) => `- ${item}`).join("\n"),
  ].join("\n");
}
