import { toPublicUrl } from "@/lib/base-path";
import { SITE_DESCRIPTION, SITE_NAME, SITE_STACK } from "@/lib/site";

export function buildDevelopersMarkdown(): string {
  return [
    `# ${SITE_NAME} Developer Docs`,
    "",
    `${SITE_NAME} API docs for AI agents and developers. ${SITE_DESCRIPTION}`,
    "",
    "## Predictable URLs",
    "",
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- MCP discovery: ${toPublicUrl("/.well-known/mcp")}`,
    `- MCP server card: ${toPublicUrl("/.well-known/mcp/server-card.json")}`,
    `- OAuth metadata: ${toPublicUrl("/.well-known/oauth-authorization-server")}`,
    `- OAuth protected resource: ${toPublicUrl("/.well-known/oauth-protected-resource")}`,
    `- Full agent docs: ${toPublicUrl("/llms-full.txt")}`,
    "",
    "## API endpoints",
    "",
    "- `POST /api/agent` streams Server-Sent Events for prompt and action requests.",
    "- `POST /api/design-feedback` publishes liked generated interfaces to the public gallery.",
    "- `POST /mcp` exposes the Streamable HTTP MCP server for tool-capable agents.",
    `- Related MCP docs: ${toPublicUrl("/mcp.md")}`,
    "",
    "## Rate limits and retries",
    "",
    "The public demo is intended for low-volume interactive evaluation. Agents should retry with backoff, send `Idempotency-Key` on mutation attempts, and respect `RateLimit-*` or `Retry-After` headers when they are present.",
  ].join("\n");
}

export function buildAuthMarkdown(): string {
  return [
    `# ${SITE_NAME} Auth Docs`,
    "",
    "Gravity AI UI currently exposes public demo endpoints. OAuth metadata is published so agents can discover the intended authorization shape before bearer-token enforcement exists.",
    "",
    "## OAuth metadata",
    "",
    `- Authorization server metadata: ${toPublicUrl("/.well-known/oauth-authorization-server")}`,
    `- OpenID configuration: ${toPublicUrl("/.well-known/openid-configuration")}`,
    `- Protected resource metadata: ${toPublicUrl("/.well-known/oauth-protected-resource")}`,
    `- MCP protected resource metadata: ${toPublicUrl("/.well-known/oauth-protected-resource/mcp")}`,
    "",
    "## Current access policy",
    "",
    "- `POST /mcp` is public and validates browser origins.",
    "- `POST /api/agent` is public but requires server-side `OPENAI_API_KEY` configuration.",
    "- `/oauth/authorize` and `/oauth/token` return structured `oauth_not_enabled` JSON because token issuance is not enabled in this metadata-only pass.",
    `- OpenAPI reference: ${toPublicUrl("/openapi.json")}`,
    "",
    "## Planned scopes",
    "",
    "- `interface:generate`: generate and refine interfaces.",
    "- `interface:read`: read public gallery interfaces.",
  ].join("\n");
}

export function buildWebhooksMarkdown(): string {
  return [
    `# ${SITE_NAME} Webhooks`,
    "",
    "Webhooks are not currently supported by Gravity AI UI.",
    "",
    "The current public product is an interactive generator, public gallery, OpenAPI document, and Streamable HTTP MCP server. Agents should poll the direct API or MCP responses instead of registering webhook callbacks.",
    "",
    `Related API docs: ${toPublicUrl("/developers.md")}`,
    "",
    "## Future webhook model",
    "",
    "- Events would cover gallery publication and long-running generation completion.",
    "- Payloads would be signed with HMAC-SHA256.",
    "- Delivery retries would use exponential backoff and structured JSON error responses.",
  ].join("\n");
}

export function buildMcpMarkdown(): string {
  return [
    `# ${SITE_NAME} MCP Docs`,
    "",
    "Gravity AI UI exposes a Streamable HTTP MCP server for public gallery lookup and interface generation.",
    "",
    "## Endpoints",
    "",
    `- Canonical MCP server: ${toPublicUrl("/mcp")}`,
    `- Well-known MCP alias: ${toPublicUrl("/.well-known/mcp")}`,
    `- Server card: ${toPublicUrl("/.well-known/mcp/server-card.json")}`,
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    "",
    "## Tools",
    "",
    "- `search_interfaces`: search public liked interface drafts.",
    "- `get_interface`: fetch a public interface payload and React code.",
    "- `generate_interface`: generate a new interface from a prompt.",
    "- `refine_interface`: refine an existing composed payload.",
    "",
    "## curl example",
    "",
    "```bash",
    `curl -X POST ${toPublicUrl("/mcp")} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  -H 'Accept: application/json, text/event-stream' \\",
    "  --data '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\"}'",
    "```",
  ].join("\n");
}

export function buildLlmsFullTxt(): string {
  return [
    `# ${SITE_NAME}`,
    "",
    `> Gravity AI UI API docs and complete agent documentation. ${SITE_DESCRIPTION}`,
    "",
    "## Product summary",
    "",
    "Gravity AI UI is an AI-powered UI generator for product interfaces. It turns natural-language prompts into validated A2UI component trees, renders them with trusted Gravity UI components, exposes copyable React code, and lets users publish liked designs to a gallery.",
    "",
    "## Core links",
    "",
    `- App: ${toPublicUrl("/")}`,
    `- Gallery: ${toPublicUrl("/gallery")}`,
    `- Developer docs: ${toPublicUrl("/docs")}`,
    `- Compare AI UI generators: ${toPublicUrl("/compare")}`,
    `- A2UI, OpenAI, and Gravity UI integration guide: ${toPublicUrl("/guides/a2ui-openai-gravity-ui")}`,
    "",
    "## API reference",
    "",
    `- OpenAPI spec: ${toPublicUrl("/openapi.json")}`,
    "- `POST /api/agent`: stream generated interface events.",
    "- `POST /api/design-feedback`: publish liked interface feedback.",
    "- API responses use structured JSON errors with `error.code` and `error.message` where routes are handled directly by the app.",
    "",
    "## MCP",
    "",
    `- MCP server: ${toPublicUrl("/mcp")}`,
    `- MCP discovery: ${toPublicUrl("/.well-known/mcp")}`,
    `- MCP server card: ${toPublicUrl("/.well-known/mcp/server-card.json")}`,
    "- Tools: `search_interfaces`, `get_interface`, `generate_interface`, `refine_interface`.",
    "",
    "```bash",
    `curl -X POST ${toPublicUrl("/mcp")} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  -H 'Accept: application/json, text/event-stream' \\",
    "  --data '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/list\"}'",
    "```",
    "",
    "## Auth",
    "",
    "OAuth metadata is published for agent discovery, but bearer-token enforcement and token issuance are not enabled in this public demo.",
    `- OAuth metadata: ${toPublicUrl("/.well-known/oauth-authorization-server")}`,
    `- Protected resource metadata: ${toPublicUrl("/.well-known/oauth-protected-resource")}`,
    "",
    "## Webhooks",
    "",
    "Webhooks are not currently supported. Agents should call the API or MCP server directly and should not attempt webhook registration.",
    "",
    "## Rate limits",
    "",
    "Use low-volume interactive requests. Respect `RateLimit-*` and `Retry-After` headers when present, and retry transient errors with backoff.",
    "",
    "## Stack",
    "",
    SITE_STACK.map((item) => `- ${item}`).join("\n"),
  ].join("\n");
}
