// Generated by scripts/generate-gravity-capabilities.mjs. Do not edit directly.

export const GRAVITY_UIKIT_VERSION = "7.39.0" as const;

export const GRAVITY_UI_BUTTON_VIEWS = [
  "normal",
  "action",
  "outlined",
  "outlined-info",
  "outlined-success",
  "outlined-warning",
  "outlined-danger",
  "outlined-utility",
  "outlined-action",
  "raised",
  "flat",
  "flat-secondary",
  "flat-info",
  "flat-success",
  "flat-warning",
  "flat-danger",
  "flat-utility",
  "flat-action",
  "normal-contrast",
  "outlined-contrast",
  "flat-contrast",
] as const;
export type GravityUiButtonView = (typeof GRAVITY_UI_BUTTON_VIEWS)[number];

export const GRAVITY_UI_TEXT_VARIANTS = [
  "display-4",
  "display-3",
  "display-2",
  "display-1",
  "header-2",
  "header-1",
  "subheader-3",
  "subheader-2",
  "subheader-1",
  "body-3",
  "body-2",
  "body-1",
  "body-short",
  "caption-2",
  "caption-1",
  "code-3",
  "code-inline-3",
  "code-2",
  "code-inline-2",
  "code-1",
  "code-inline-1",
] as const;
export type GravityUiTextVariant = (typeof GRAVITY_UI_TEXT_VARIANTS)[number];

export const GRAVITY_UI_TEXT_COLORS = [
  "primary",
  "complementary",
  "secondary",
  "hint",
  "info",
  "info-heavy",
  "positive",
  "positive-heavy",
  "warning",
  "warning-heavy",
  "danger",
  "danger-heavy",
  "utility",
  "utility-heavy",
  "misc",
  "misc-heavy",
  "brand",
  "link",
  "link-hover",
  "link-visited",
  "link-visited-hover",
  "dark-primary",
  "dark-complementary",
  "dark-secondary",
  "light-primary",
  "light-complementary",
  "light-secondary",
  "light-hint",
  "inverted-primary",
  "inverted-complementary",
  "inverted-secondary",
  "inverted-hint",
] as const;
export type GravityUiTextColor = (typeof GRAVITY_UI_TEXT_COLORS)[number];

export const GRAVITY_UI_CARD_CONTAINER_VIEWS = [
  "outlined",
  "filled",
  "raised",
] as const;
export type GravityUiCardContainerView = (typeof GRAVITY_UI_CARD_CONTAINER_VIEWS)[number];

export const GRAVITY_UI_CARD_THEMES = [
  "normal",
  "info",
  "success",
  "warning",
  "danger",
  "utility",
] as const;
export type GravityUiCardTheme = (typeof GRAVITY_UI_CARD_THEMES)[number];
