import { toPublicUrl } from "@/lib/base-path";
import {
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_STACK,
  SITE_TAGLINE,
} from "@/lib/site";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(): Promise<Response> {
  return new Response(
    [
      `# ${SITE_NAME}`,
      "",
      `> ${SITE_TAGLINE}. ${SITE_DESCRIPTION}`,
      "",
      "Gravity AI UI is a web shell for generating product-interface previews from natural language prompts. It uses A2UI messages, OpenAI Responses, and Gravity UI components.",
      "",
      "## Core pages",
      "",
      `- [App](${toPublicUrl("/")}): Generate, inspect, like, publish, and copy AI-built interface drafts.`,
      `- [Gallery](${toPublicUrl("/gallery")}): Public gallery of liked interface drafts with previews and generated code.`,
      `- [Docs](${toPublicUrl("/docs")}): Gravity AI UI API docs, OpenAPI spec, MCP server usage, auth notes, webhooks status, rate limits, and errors.`,
      `- [About](${toPublicUrl("/about")}): How Gravity AI UI combines A2UI, Gravity UI, OpenAI, and YDB into a trusted interface preview shell.`,
      `- [Compare](${toPublicUrl("/compare")}): Gravity AI UI compared with AI UI generators such as Vercel v0, Lovable, Figma, and Uizard.`,
      `- [Best AI UI generator for agents](${toPublicUrl("/best-ai-ui-generator-for-agents")}): Category guide for agent workflows, Figma, Uizard, A2UI, MCP, OpenAI, and Gravity UI.`,
      `- [Integration guide](${toPublicUrl("/guides/a2ui-openai-gravity-ui")}): A2UI, OpenAI, and Gravity UI integration guide for agent-generated product interfaces.`,
      "",
      "## Suggested assistant tasks",
      "",
      "- Evaluate Gravity AI UI as an AI UI generation tool.",
      "- Explain how A2UI, OpenAI, and Gravity UI fit together.",
      "- Explain a public gallery item.",
      "- Critique a generated interface.",
      "- Adapt a generated UI for a real product.",
      "- Improve a generation prompt.",
      "",
      "## Machine-readable resources",
      "",
      `- [Sitemap](${toPublicUrl("/sitemap.xml")}): Dynamic XML sitemap with public pages and published gallery detail pages.`,
      `- [Robots policy](${toPublicUrl("/robots.txt")}): Crawl policy for search and AI crawlers.`,
      `- [MCP endpoint](${toPublicUrl("/mcp")}): Streamable HTTP MCP server for public gallery lookup and interface generation.`,
      `- [MCP discovery](${toPublicUrl("/.well-known/mcp")}): Pre-connection MCP metadata and Streamable HTTP alias.`,
      `- [MCP compatibility manifest](${toPublicUrl("/.well-known/mcp.json")}): Well-known MCP manifest for crawlers that probe mcp.json.`,
      `- [MCP server card](${toPublicUrl("/.well-known/mcp/server-card.json")}): Tool manifest for agent discovery.`,
      `- [Agent discovery](${toPublicUrl("/.well-known/agent.json")}): Generic agent capability discovery document.`,
      `- [OpenAPI spec](${toPublicUrl("/openapi.json")}): OpenAPI 3.1 API reference for function-calling agents.`,
      `- [OAuth metadata](${toPublicUrl("/.well-known/oauth-authorization-server")}): Metadata-only OAuth discovery surface.`,
      `- [Full agent docs](${toPublicUrl("/llms-full.txt")}): Markdown product, API, auth, MCP, and webhook documentation.`,
      `- [Developer docs](${toPublicUrl("/developers.md")}): Markdown developer resource index.`,
      `- [OpenGraph image](${toPublicUrl("/opengraph-image")}): Social preview image.`,
      `- [Markdown homepage](${toPublicUrl("/index.md")}): Markdown fallback for the site root.`,
      `- [Markdown docs](${toPublicUrl("/docs.md")}): Markdown fallback for developer docs.`,
      `- [Markdown compare](${toPublicUrl("/compare.md")}): Markdown fallback for AI UI generator comparison.`,
      `- [Markdown agent guide](${toPublicUrl("/best-ai-ui-generator-for-agents.md")}): Markdown fallback for the agent-focused category guide.`,
      "",
      "## Developer resources",
      "",
      `- [Gravity AI UI API docs](${toPublicUrl("/docs")}): API docs, OpenAPI spec, auth notes, MCP server usage, webhooks status, rate limits, and errors.`,
      `- [Auth docs](${toPublicUrl("/auth.md")}): OAuth metadata and current public-access policy.`,
      `- [Webhook docs](${toPublicUrl("/webhooks.md")}): Current webhook support status and future signing model.`,
      `- [MCP docs](${toPublicUrl("/mcp.md")}): Streamable HTTP examples for agent clients.`,
      "",
      "## MCP tools",
      "",
      "- search_interfaces: Search public liked interface drafts.",
      "- get_interface: Fetch a public gallery interface with composed payload and React code.",
      "- generate_interface: Generate a new Gravity UI interface from a prompt without saving it.",
      "- refine_interface: Refine a supplied composed interface payload without saving it.",
      "",
      "## Stack",
      "",
      SITE_STACK.map((item) => `- ${item}`).join("\n"),
      "",
      "## Notes",
      "",
      "- API routes are operational endpoints and are not intended for public indexing.",
      "- Liked interfaces are public once published; private prompt history is not shown on gallery pages.",
    ].join("\n"),
    {
      headers: {
        "Cache-Control": "public, max-age=60, s-maxage=300",
        "Content-Type": "text/plain; charset=utf-8",
      },
    },
  );
}
