export const POPULAR_STARTER_PROMPTS = [
  "Build a compact incident triage panel with severity, owner, and next actions.",
  "Create an outage command center with service status, timeline, and response tasks.",
  "Design a post-incident review workspace with impact, causes, and follow-ups.",
  "Make an on-call handoff dashboard with active alerts, owners, and escalation paths.",
  "Create a maintenance window planner with affected systems and approval steps.",
  "Build a release health monitor with deployment status, metrics, and rollback action.",
  "Design a service reliability scorecard with SLOs, risks, and action items.",
  "Create a critical alert review panel with signal quality and recommended routing.",
  "Build a runbook execution checklist with confirmations and progress tracking.",
  "Design a customer impact assessment form for active incidents.",
  "Create a support escalation form with priority choices and owner assignment.",
  "Build a customer support queue dashboard with SLA risk and quick filters.",
  "Design a helpdesk ticket detail page with history, sentiment, and next reply.",
  "Create a refund approval workflow with customer context and policy checks.",
  "Build a bug report intake form with reproduction steps and environment fields.",
  "Design a customer health dashboard with accounts at risk and renewal signals.",
  "Create a customer onboarding tracker with milestones and blockers.",
  "Build an account notes panel with recent activity and follow-up actions.",
  "Design a churn risk review board with reasons, owner, and retention playbook.",
  "Create a support macro picker with categories, preview, and confidence notes.",
  "Build a product roadmap board with priorities, status, and trade-off notes.",
  "Create a sprint planning workspace with backlog, capacity, and commitments.",
  "Design a feature brief review page with goals, risks, and launch checklist.",
  "Build a product requirements intake form with persona, problem, and success metric.",
  "Create a roadmap voting dashboard with themes, confidence, and dependencies.",
  "Design a release notes editor with highlights, breaking changes, and approvals.",
  "Build a beta feedback dashboard with themes and top customer quotes.",
  "Create a feature flag control panel with rollout stages and safety checks.",
  "Design an experiment review page with hypothesis, variants, and decision state.",
  "Build a product discovery interview tracker with insights and next steps.",
  "Create an executive KPI dashboard with revenue, retention, and operational alerts.",
  "Build a marketing analytics dashboard with channels, spend, and conversion.",
  "Design a sales pipeline dashboard with forecast, stages, and blocked deals.",
  "Create a usage analytics panel with cohorts, retention, and feature adoption.",
  "Build a finance overview with burn, runway, and budget variance.",
  "Design a warehouse operations dashboard with inventory, delays, and exceptions.",
  "Create a content performance dashboard with traffic, engagement, and actions.",
  "Build a data quality dashboard with failed checks, owners, and trends.",
  "Design a marketplace seller dashboard with orders, ratings, and payouts.",
  "Create a team productivity dashboard with cycle time, focus, and blockers.",
  "Build a multi-step vendor onboarding form with documents and risk checks.",
  "Create a contract review workflow with clauses, approvals, and due dates.",
  "Design a procurement request form with budget, vendor, and justification.",
  "Build an access request workflow with role selection and approver routing.",
  "Create a travel expense submission form with receipts and policy validation.",
  "Design an equipment checkout form with inventory status and return date.",
  "Build a document approval flow with reviewers, comments, and final sign-off.",
  "Create a meeting room booking form with capacity and equipment needs.",
  "Design a data export request workflow with scope and privacy review.",
  "Build a project intake form with goals, stakeholders, and timeline.",
  "Create an invoice approval dashboard with exceptions and payment status.",
  "Build a budget planning workspace with categories, owners, and variance notes.",
  "Design a subscription management panel with plans, invoices, and usage.",
  "Create a purchase order tracker with vendor status and receiving details.",
  "Build a cash flow forecast dashboard with scenarios and risk notes.",
  "Design a tax document checklist with upload status and missing items.",
  "Create a payroll exception review panel with employees and corrections.",
  "Build a billing dispute workflow with evidence and resolution actions.",
  "Design a vendor risk dashboard with contracts, renewals, and compliance.",
  "Create an expense policy assistant interface with violations and suggestions.",
  "Build a hiring pipeline dashboard with candidates, stages, and interview feedback.",
  "Create an employee onboarding checklist with tasks, owners, and due dates.",
  "Design a performance review workspace with goals, feedback, and calibration.",
  "Build a time-off approval panel with coverage conflicts and team calendar.",
  "Create a skills matrix dashboard with gaps, levels, and training actions.",
  "Design an internal transfer request workflow with manager approvals.",
  "Build a compensation review page with bands, changes, and rationale.",
  "Create a recruiting intake form with role requirements and interview plan.",
  "Design a pulse survey results dashboard with themes and follow-ups.",
  "Build a workforce planning dashboard with headcount, roles, and hiring needs.",
  "Create a campaign planning dashboard with goals, assets, and launch checklist.",
  "Build a lead scoring review panel with signals and routing recommendations.",
  "Design an email campaign editor workflow with audience, content, and approval.",
  "Create a social media calendar with post status and performance targets.",
  "Build an ad creative review board with variants, feedback, and decisions.",
  "Design a landing page QA checklist with sections and launch blockers.",
  "Create an event registration dashboard with attendees and follow-up tasks.",
  "Build a partner pipeline dashboard with opportunities and co-marketing actions.",
  "Design a press outreach tracker with contacts, status, and talking points.",
  "Create a brand asset request workflow with usage context and approvals.",
  "Build a developer portal home with APIs, keys, and quickstart actions.",
  "Create a CI/CD pipeline dashboard with builds, failures, and deploy controls.",
  "Design a pull request review queue with risk level and reviewer assignment.",
  "Build an API key management page with scopes, rotation, and audit history.",
  "Create a feature flag dashboard with environments and rollout rules.",
  "Design a database migration checklist with backups, checks, and rollback.",
  "Build a log search interface with filters, saved queries, and anomaly markers.",
  "Create a cloud cost optimization dashboard with services and recommendations.",
  "Design an environment status page with regions, versions, and incidents.",
  "Build a developer onboarding checklist with access, docs, and first tasks.",
  "Create an AI assistant control panel with tools, memory, and safety settings.",
  "Build an AI prompt evaluation dashboard with scores, examples, and regressions.",
  "Design a model comparison workspace with latency, quality, and cost trade-offs.",
  "Create an agent task queue with status, approvals, and retry actions.",
  "Build a knowledge base ingestion monitor with sources and sync errors.",
  "Design a human review queue for AI outputs with confidence and edits.",
  "Create an AI workflow builder with steps, tools, and guardrails.",
  "Build a chat quality dashboard with conversations, ratings, and failure modes.",
  "Design a prompt library manager with tags, versions, and owner notes.",
  "Create an automation audit log with agent actions and approval history.",
  "Build a patient appointment dashboard with upcoming visits and care gaps.",
  "Create a wellness habit tracker with goals, streaks, and reminders.",
  "Design a clinic intake form with symptoms, insurance, and priority triage.",
  "Build a medication adherence dashboard with doses, refills, and alerts.",
  "Create a care plan checklist with tasks, owners, and progress.",
  "Design a fitness coaching panel with workouts, recovery, and recommendations.",
  "Build a mental health check-in form with mood, stressors, and support actions.",
  "Create a nutrition planning interface with meals, macros, and shopping list.",
  "Design a telehealth visit summary with notes, follow-ups, and prescriptions.",
  "Build a lab results review page with ranges, flags, and next steps.",
  "Create a course progress dashboard with lessons, assignments, and deadlines.",
  "Build a lesson planning workspace with objectives, activities, and materials.",
  "Design a student performance dashboard with grades, risks, and interventions.",
  "Create a training enrollment form with prerequisites and manager approval.",
  "Build a certification tracker with progress, attempts, and renewal dates.",
  "Design a classroom attendance dashboard with trends and follow-up actions.",
  "Create a learning path builder with modules, quizzes, and milestones.",
  "Build a tutor session planner with goals, notes, and homework.",
  "Design a workshop feedback dashboard with ratings, themes, and improvements.",
  "Create a scholarship application review panel with eligibility and scoring.",
  "Build an ecommerce order management dashboard with fulfillment exceptions.",
  "Create a product detail editor with variants, inventory, and publishing checks.",
  "Design a returns management workflow with reason codes and refund actions.",
  "Build a cart abandonment dashboard with recovery campaigns and segments.",
  "Create a merchandising planner with collections, promotions, and stock risk.",
  "Design a loyalty program dashboard with tiers, rewards, and engagement.",
  "Build a seller onboarding checklist with documents and payout setup.",
  "Create a price change approval workflow with margin impact and competitors.",
  "Design a review moderation queue with sentiment, flags, and response actions.",
  "Build an inventory replenishment dashboard with forecasts and purchase needs.",
  "Create a trip planning dashboard with itinerary, bookings, and travel alerts.",
  "Build a hotel operations panel with arrivals, housekeeping, and room issues.",
  "Design a flight disruption assistant with rebooking options and customer impact.",
  "Create a restaurant reservation manager with tables, waitlist, and notes.",
  "Build a concierge request dashboard with guest preferences and task status.",
  "Design a travel expense planner with categories, approvals, and receipts.",
  "Create a tour booking workflow with availability, guests, and payment status.",
  "Build a venue event schedule with rooms, vendors, and setup tasks.",
  "Design a guest feedback dashboard with themes and service recovery actions.",
  "Create a property maintenance tracker with requests, priority, and vendors.",
  "Build an editorial calendar with drafts, owners, and publication status.",
  "Create a podcast production checklist with episodes, guests, and assets.",
  "Design a video analytics dashboard with watch time, retention, and actions.",
  "Build a content brief generator interface with audience, angle, and SEO goals.",
  "Create a newsletter planning dashboard with segments, topics, and approvals.",
  "Design a media asset library with filters, usage rights, and download actions.",
  "Build a community moderation dashboard with reports, users, and decisions.",
  "Create a publishing workflow with review stages, comments, and schedule.",
  "Design a creator sponsorship tracker with deals, deliverables, and payments.",
  "Build a documentation backlog with topics, status, and reviewer assignment.",
  "Create a security review dashboard with vulnerabilities, severity, and owners.",
  "Build an access audit panel with users, roles, and risky permissions.",
  "Design a compliance evidence tracker with controls, documents, and status.",
  "Create a phishing report triage queue with sender, indicators, and actions.",
  "Build a risk register with probability, impact, mitigation, and owners.",
  "Design a privacy request workflow with identity checks and due dates.",
  "Create a vendor security assessment form with controls and scoring.",
  "Build a policy exception approval page with rationale and expiry date.",
  "Design an audit finding remediation dashboard with evidence and deadlines.",
  "Create a security incident timeline with events, indicators, and containment.",
  "Build a database table explorer with schema, samples, and query actions.",
  "Create a data pipeline monitor with freshness, failures, and rerun controls.",
  "Design a dataset catalog page with owners, lineage, and access requests.",
  "Build a backup verification dashboard with jobs, retention, and restore checks.",
  "Create a data labeling queue with tasks, guidelines, and quality score.",
  "Design a report builder with dimensions, filters, and export options.",
  "Build a metrics definition registry with formulas, owners, and usage.",
  "Create a data contract review workflow with producers and consumers.",
  "Design a storage cost dashboard with volumes, growth, and cleanup actions.",
  "Build a data access approval form with purpose, duration, and sensitivity.",
  "Create a SaaS admin shell with left navigation, account status, and quick actions.",
  "Build a workspace switcher dashboard with projects, teams, and notifications.",
  "Design a settings center with navigation groups and searchable preferences.",
  "Create an analytics app shell with top navigation and saved reports.",
  "Build a CRM workspace with account navigation and recent activity.",
  "Design a project management shell with sidebar sections and task summary.",
  "Create a billing portal shell with invoices, plan, and payment method tabs.",
  "Build a developer console shell with APIs, environments, and logs navigation.",
  "Design a knowledge base shell with categories, search, and featured articles.",
  "Create a command center shell with status, alerts, and operational shortcuts.",
  "Build a personal weekly planner with priorities, calendar, and focus blocks.",
  "Create a habit dashboard with goals, streaks, and reflection prompts.",
  "Design a personal finance tracker with budgets, bills, and savings goals.",
  "Build a job search tracker with applications, contacts, and interview prep.",
  "Create a meal planning dashboard with recipes, groceries, and prep schedule.",
  "Design a reading list manager with priorities, notes, and progress.",
  "Build a home maintenance checklist with rooms, tasks, and due dates.",
  "Create a family schedule board with events, chores, and reminders.",
  "Design a goal review workspace with milestones, risks, and next actions.",
  "Build a decision journal with options, criteria, and follow-up review.",
  "Create an asset inventory dashboard with location, condition, and ownership.",
  "Build a fleet maintenance planner with vehicles, service dates, and issues.",
  "Design a manufacturing quality dashboard with defects, batches, and actions.",
  "Create a construction project tracker with milestones, permits, and risks.",
  "Build a real estate listing manager with leads, showings, and offers.",
  "Design a nonprofit donation dashboard with campaigns, donors, and follow-ups.",
  "Create a legal matter tracker with deadlines, documents, and client updates.",
  "Build an insurance claim review panel with evidence, coverage, and decisions.",
  "Design a loan application workflow with documents, checks, and approval state.",
  "Create a board meeting prep dashboard with agenda, materials, and decisions.",
] as const;

export function pickRandomStarterPrompts(
  count = 3,
  random: () => number = Math.random,
) {
  const prompts = [...POPULAR_STARTER_PROMPTS];

  for (let index = prompts.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1));
    [prompts[index], prompts[swapIndex]] = [prompts[swapIndex], prompts[index]];
  }

  return prompts.slice(0, count);
}
