export const POPULAR_STARTER_PROMPTS = [
  "Create an AI assistant setup wizard with role selection, autonomy level, tool access, and launch review.",
  "Design an agent memory inspector with saved facts, conflicts, confidence, and edit actions.",
  "Build an AI workflow builder for research tasks with steps, tools, approvals, and retry controls.",
  "Create a prompt version compare view with diffs, evaluation notes, and rollback actions.",
  "Design a human review queue for AI outputs with confidence, policy flags, and correction fields.",
  "Build an agent run detail page with timeline, tool calls, intermediate artifacts, and final decision.",
  "Create a model routing rule editor with cost limits, latency targets, and fallback behavior.",
  "Design a knowledge ingestion review flow with source quality, chunks, and sync errors.",
  "Build an automation permission request panel with scopes, risk notes, and approver routing.",
  "Create an AI eval case authoring form with input, expected behavior, rubric, and tags.",
  "Design a pull request review surface with changed files, risk level, reviewers, and CI links.",
  "Build a database migration runbook with backup confirmation, validation queries, and rollback steps.",
  "Create an API key rotation flow with affected apps, scopes, expiry, and copy-safe actions.",
  "Design a log investigation workspace with filters, saved query chips, and suspected anomaly rows.",
  "Build a feature flag rollout planner with cohorts, safeguards, kill switch, and progress.",
  "Create a developer onboarding guide with access steps, first ticket, docs, and mentor owner.",
  "Design an environment comparison view with versions, config drift, and deploy eligibility.",
  "Build a webhook delivery debugger with failed attempts, payload preview, and replay controls.",
  "Create a schema explorer with tables, columns, samples, and access request action.",
  "Design a package release checklist with changelog, semver risk, tests, and publish approval.",
  "Create a brand campaign brief editor with audience, message pillars, channels, and approval state.",
  "Design a social media post calendar with drafts, owners, scheduled slots, and asset links.",
  "Build an ad creative review room with variants, comments, usage rights, and decision buttons.",
  "Create a press outreach tracker with journalist contacts, pitches, embargo notes, and next steps.",
  "Design a newsletter issue planner with sections, segments, subject lines, and send readiness.",
  "Build a landing page QA surface with copy checks, analytics tags, launch blockers, and sign-off.",
  "Create a media asset library view with filters, licenses, expiration dates, and download actions.",
  "Design a content brief generator form with search intent, angle, outline, and SEO constraints.",
  "Build a podcast episode production board with guests, recording tasks, assets, and approvals.",
  "Create a creator sponsorship tracker with deliverables, payment milestones, and brand safety notes.",
  "Design a procurement request flow with vendor details, budget impact, policy checks, and approvers.",
  "Build a contract clause review panel with risky terms, fallback language, owners, and due dates.",
  "Create an invoice exception resolver with line items, evidence, payment hold, and approval actions.",
  "Design a travel expense claim form with receipts, policy warnings, and reimbursement summary.",
  "Build a subscription change panel with current plan, next plan, usage limits, and renewal switch.",
  "Create a purchase order receiving screen with partial shipments, discrepancies, and vendor notes.",
  "Design a billing dispute case view with evidence, customer history, coverage, and resolution choices.",
  "Build a budget reallocation workflow with source category, destination category, and impact review.",
  "Create a vendor onboarding checklist with required documents, tax details, and risk rating.",
  "Design a board approval packet with agenda items, decision options, owners, and meeting materials.",
  "Build an employee onboarding journey with pre-start tasks, equipment pickup, access, and buddy info.",
  "Create a time-off approval panel with coverage conflicts, team calendar notes, and manager actions.",
  "Design a performance review writing workspace with goals, peer feedback, calibration, and draft state.",
  "Build a recruiting intake form with hiring goals, interview plan, must-have skills, and compensation range.",
  "Create an internal transfer request view with current manager, target team, rationale, and approvals.",
  "Design a compensation adjustment review with band position, rationale, effective date, and audit notes.",
  "Build a team skills matrix editor with levels, gaps, learning options, and owner assignments.",
  "Create a pulse survey follow-up planner with themes, proposed actions, owners, and deadlines.",
  "Design an interview debrief room with candidate signal, panel notes, concerns, and hiring decision.",
  "Build a manager one-on-one prep surface with topics, commitments, blockers, and next meeting plan.",
  "Create a lesson planning workspace with objectives, activities, materials, timing, and assessment.",
  "Design a classroom attendance intervention view with absent students, reasons, guardians, and actions.",
  "Build a scholarship application review panel with eligibility, scoring, essays, and decision state.",
  "Create a course module builder with lessons, quizzes, prerequisites, and publish readiness.",
  "Design a tutor session planner with student goals, prior homework, exercises, and follow-up tasks.",
  "Build a workshop facilitation checklist with room setup, materials, roles, and contingency plan.",
  "Create a certification renewal tracker with attempts, deadlines, evidence, and reminder settings.",
  "Design a student accommodation request workflow with documentation, review notes, and approvals.",
  "Build a learning path recommendation page with modules, skill gaps, time estimate, and enrollment action.",
  "Create a grading rubric editor with criteria, levels, point ranges, and feedback snippets.",
  "Design a clinic intake flow with symptoms, insurance, priority triage, and appointment options.",
  "Build a lab result review page with biomarkers, ranges, flags, patient notes, and next steps.",
  "Create a medication refill request panel with adherence, pharmacy, warnings, and clinician approval.",
  "Design a care plan checklist with tasks, responsible roles, due dates, and progress status.",
  "Build a telehealth visit summary with diagnosis notes, prescriptions, referrals, and follow-ups.",
  "Create a mental health check-in form with mood, stressors, support contacts, and safety plan.",
  "Design a fitness coaching plan with workouts, recovery score, nutrition notes, and adjustment slider.",
  "Build a nutrition meal planner with macro targets, grocery list, recipes, and prep schedule.",
  "Create a physical therapy session tracker with exercises, pain scale, progress, and homework.",
  "Design a patient referral coordinator with specialist options, documents, availability, and booking action.",
  "Create a trip itinerary builder with cities, bookings, transport choices, and travel warnings.",
  "Design a flight disruption assistant with passenger impact, rebooking options, vouchers, and notifications.",
  "Build a hotel front desk panel with arrivals, room readiness, guest notes, and issue escalation.",
  "Create a restaurant reservation manager with tables, waitlist, dietary notes, and seating action.",
  "Design a concierge request workspace with guest preferences, vendor options, and service recovery.",
  "Build a venue setup schedule with rooms, vendors, equipment, and day-of checklist.",
  "Create a tour booking flow with availability, guests, add-ons, waiver status, and payment details.",
  "Design a property maintenance request panel with photos, priority, vendor assignment, and status.",
  "Build a travel packing assistant with weather, itinerary needs, luggage limits, and checklist progress.",
  "Create a museum visit planner with exhibit zones, accessibility needs, tickets, and recommended route.",
  "Design a product detail editor with variants, inventory, images, SEO fields, and publish checks.",
  "Build a returns authorization workflow with reason codes, condition notes, refund method, and fraud signals.",
  "Create a price change approval panel with margin impact, competitor references, and effective date.",
  "Design a merchandising collection planner with products, promotions, stock risk, and launch tasks.",
  "Build a seller payout setup checklist with identity checks, bank details, tax forms, and status.",
  "Create a loyalty reward rule editor with tiers, earning rules, exclusions, and preview.",
  "Design a review moderation queue with flagged text, sentiment, policy reason, and response action.",
  "Build a product bundle composer with included items, discount logic, availability, and validation alerts.",
  "Create a store pickup coordinator with orders, staging location, customer arrival, and handoff state.",
  "Design a gift card support case view with balance history, fraud notes, and resolution actions.",
  "Build an access audit review with risky permissions, inactive users, owners, and revoke actions.",
  "Create a phishing report triage panel with sender, headers, indicators, and containment steps.",
  "Design a privacy request workflow with identity verification, data scope, due date, and export status.",
  "Build a policy exception approval page with rationale, compensating controls, expiry, and approver notes.",
  "Create a vendor security questionnaire review with control gaps, evidence links, and risk score.",
  "Design an audit evidence collection surface with controls, documents, owners, and missing proof.",
  "Build a risk register editor with probability, impact, mitigations, owner, and review cadence.",
  "Create a security incident timeline with events, indicators, containment actions, and communication notes.",
  "Design a secrets exposure response flow with affected systems, rotation steps, and verification.",
  "Build a compliance training assignment panel with audience, due date, exceptions, and reminder switch.",
  "Create a dataset catalog page with lineage, owner, sensitivity, sample fields, and access request.",
  "Design a report builder with dimensions, filters, preview rows, and export options.",
  "Build a data labeling task queue with instructions, quality score, reviewer notes, and submit action.",
  "Create a data contract review workflow with producers, consumers, schema changes, and approval state.",
  "Design a research study intake form with hypothesis, cohort, metrics, risks, and review board notes.",
  "Build an experiment decision page with variants, evidence, guardrails, and ship-or-stop action.",
  "Create a metrics definition registry entry with formula, owner, caveats, and downstream usage.",
  "Design a data access request form with purpose, duration, sensitivity, and approver routing.",
  "Build a backup restore drill checklist with target system, restore point, validation, and sign-off.",
  "Create a survey analysis workspace with respondent segments, notable quotes, themes, and action plan.",
  "Design a personal weekly planning board with focus blocks, priorities, chores, and reflection.",
  "Build a reading list manager with books, notes, priority, reading progress, and next pick.",
  "Create a job search tracker with applications, contacts, interview prep, and follow-up dates.",
  "Design a household maintenance checklist with rooms, recurring tasks, costs, and service providers.",
  "Build a family schedule board with events, pickups, chores, reminders, and conflict alerts.",
  "Create a decision journal entry with options, criteria, confidence, outcome date, and revisit reminder.",
  "Design a personal finance budget planner with bills, savings goals, spending limits, and warnings.",
  "Build a habit reflection surface with streaks, blockers, mood notes, and next commitment.",
  "Create a meal prep planner with recipes, grocery groups, cooking order, and storage notes.",
  "Design a home automation scene editor with room switches, temperature slider, security state, and schedule.",
  "Build an editorial assignment board with article ideas, writers, stages, deadlines, and reviewer notes.",
  "Create a screenplay scene organizer with characters, locations, beats, continuity notes, and revision action.",
  "Design a video production shot list with locations, equipment, talent, timing, and approval status.",
  "Build a photography client proofing flow with selects, retouch notes, usage rights, and invoice link.",
  "Create a music release planner with tracks, artwork, distribution checklist, and promotion tasks.",
  "Design a live stream control checklist with scenes, moderators, sponsor reads, and emergency fallback.",
  "Build a design critique board with frames, comments, severity, owners, and resolution status.",
  "Create a translation review workspace with source text, target variants, glossary notes, and approval.",
  "Design a book launch campaign planner with reviewers, events, assets, and milestone progress.",
  "Build a comic issue production tracker with script, pencils, inks, lettering, and print handoff.",
  "Create a guild raid roster planner with roles, attendance, loot notes, and ready check.",
  "Design a tabletop RPG session prep surface with scenes, NPCs, clues, maps, and pacing.",
  "Build a game patch notes editor with balance changes, known issues, assets, and publish approval.",
  "Create a tournament bracket admin with player check-in, match results, disputes, and stream schedule.",
  "Design a player support appeal review with ban reason, evidence, history, and decision actions.",
  "Build a game economy tuning panel with item prices, drop rates, warnings, and rollout controls.",
  "Create a community event signup flow with teams, roles, rules acceptance, and reminders.",
  "Design a quest authoring tool with objectives, rewards, prerequisites, and localization notes.",
  "Build a beta tester feedback room with devices, bug categories, repro notes, and severity choice.",
  "Create a game accessibility review checklist with settings, blockers, test notes, and owner actions.",
  "Design a grant application review panel with eligibility, budget, impact story, and scoring rubric.",
  "Build a volunteer shift scheduler with roles, availability, training status, and reminder actions.",
  "Create a city service request intake flow with location, category, photos, and routing.",
  "Design a public meeting agenda builder with speakers, time boxes, documents, and vote items.",
  "Build a donation thank-you workflow with donor segment, message preview, and follow-up tasks.",
  "Create a disaster relief supply coordinator with needs, locations, transport, and urgency.",
  "Design a community garden plot manager with applicants, assignments, rules, and seasonal tasks.",
  "Build a library hold request panel with patron info, item availability, pickup branch, and alerts.",
  "Create a nonprofit program outcome report with activities, participant notes, evidence, and next actions.",
  "Design a citizen feedback moderation queue with topics, sentiment, duplicates, and response owner.",
  "Build a fleet maintenance planner with vehicles, service intervals, defects, and mechanic assignment.",
  "Create a field inspection form with site conditions, photos checklist, findings, and sign-off.",
  "Design a warehouse pick-pack flow with order batches, substitutions, packing notes, and exceptions.",
  "Build a delivery route adjustment panel with stops, delays, driver notes, and customer notifications.",
  "Create a manufacturing batch release checklist with tests, deviations, approvals, and quarantine switch.",
  "Design an equipment checkout kiosk with item condition, borrower details, due date, and deposit status.",
  "Build a construction daily report with crews, weather, work completed, blockers, and safety notes.",
  "Create a maintenance work order board with priority, parts required, technician, and completion proof.",
  "Design a farm harvest planner with fields, crews, equipment, storage, and quality checks.",
  "Build a lab sample chain-of-custody surface with transfers, storage conditions, tests, and alerts.",
  "Create a museum exhibit installation tracker with artifacts, conservation notes, crates, and curators.",
  "Design an archeology dig log with trench details, finds, photos, catalog IDs, and next actions.",
  "Build a clinical trial visit coordinator with participants, procedures, deviations, and document status.",
  "Create a space mission anomaly review panel with subsystem telemetry, hypotheses, and command approval.",
  "Design an observatory night plan with targets, weather windows, instruments, and priority changes.",
  "Build a chemistry inventory request flow with hazards, storage, quantities, and approval routing.",
  "Create a research paper submission checklist with authors, figures, ethics, and journal requirements.",
  "Design a specimen collection planner with sites, permits, containers, and preservation notes.",
  "Build a grant budget justification editor with categories, assumptions, reviewers, and compliance checks.",
  "Create a conference poster review workspace with sections, figures, accessibility, and print readiness.",
  "Design a real estate showing scheduler with clients, properties, time windows, and feedback capture.",
  "Build a tenant move-in checklist with deposits, keys, inspections, utilities, and welcome packet.",
  "Create a construction change order workflow with scope, cost impact, drawings, and approvals.",
  "Design a manufacturing quality hold review with batch data, defects, containment, and disposition.",
  "Build a facility space request form with capacity, layout needs, equipment, and approval notes.",
  "Create an insurance claim evidence review with coverage, photos, documents, adjuster notes, and decision.",
  "Design a loan application underwriting panel with documents, ratios, conditions, and approval state.",
  "Build a legal matter timeline with filings, deadlines, parties, documents, and next hearing.",
  "Create an architecture materials selection board with samples, costs, sustainability notes, and decision.",
  "Design a repair estimate approval flow with parts, labor, warranty, customer consent, and payment.",
  "Build a support ticket reply composer with customer context, sentiment, macros, and policy warnings.",
  "Create an account onboarding workspace with milestones, blockers, contacts, and kickoff notes.",
  "Design a renewal negotiation prep panel with usage, stakeholders, risks, and concession options.",
  "Build a customer training session planner with agenda, attendees, exercises, and follow-up tasks.",
  "Create a bug reproduction intake form with environment, steps, expected result, and attachments checklist.",
  "Design a refund review flow with order history, policy rules, fraud notes, and customer message.",
  "Build a churn rescue playbook with reasons, save offers, owner assignment, and next contact.",
  "Create an implementation handoff form with scope, integrations, risks, and launch date.",
  "Design a customer advisory board agenda with participants, topics, feedback capture, and action items.",
  "Build a service recovery case view with guest issue, compensation options, staff owner, and follow-up.",
  "Create a command palette configuration panel with actions, shortcuts, permissions, and preview.",
  "Design a settings center with grouped preferences, search, toggles, and save review.",
  "Build a workspace switcher shell with recent projects, teams, notifications, and quick actions.",
  "Create a mobile app permission onboarding flow with benefits, privacy notes, and skip paths.",
  "Design a calendar rescheduling assistant with conflicts, attendee priorities, and suggested slots.",
  "Build a visual rule builder with conditions, operators, validation, and test cases.",
  "Create a notification preference center with channels, quiet hours, topic subscriptions, and preview.",
  "Design a file import wizard with mapping, validation errors, duplicates, and commit step.",
  "Build a role-based access editor with users, groups, inherited permissions, and change summary.",
  "Create a launch control room with checklist, owners, timeline, alerts, and final go/no-go action.",
] as const;

export function pickRandomStarterPrompts(
  count = 3,
  random: () => number = Math.random,
) {
  const prompts = [...POPULAR_STARTER_PROMPTS];

  for (let index = prompts.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1));
    [prompts[index], prompts[swapIndex]] = [prompts[swapIndex], prompts[index]];
  }

  return prompts.slice(0, count);
}
