export const POPULAR_STARTER_PROMPTS = [
  "Create an AI assistant setup wizard with role selection, autonomy level, tool access, and launch review.",
  "Design an agent memory inspector with saved facts, conflicts, confidence, and edit actions.",
  "Build an AI workflow builder for research tasks with steps, tools, approvals, and retry controls.",
  "Create a prompt version compare view with diffs, evaluation notes, and rollback actions.",
  "Design a human review queue for AI outputs with confidence, policy flags, and correction fields.",
  "Build an agent run detail page with timeline, tool calls, intermediate artifacts, and final decision.",
  "Create a model routing rule editor with cost limits, latency targets, and fallback behavior.",
  "Design a knowledge ingestion review flow with source quality, chunks, and sync errors.",
  "Build an automation permission request panel with scopes, risk notes, and approver routing.",
  "Create an AI eval case authoring form with input, expected behavior, rubric, and tags.",
  "Design a pull request review surface with changed files, risk level, reviewers, and CI links.",
  "Build a database migration runbook with backup confirmation, validation queries, and rollback steps.",
  "Create an API key rotation flow with affected apps, scopes, expiry, and copy-safe actions.",
  "Design a log investigation workspace with filters, saved query chips, and suspected anomaly rows.",
  "Build a feature flag rollout planner with cohorts, safeguards, kill switch, and progress.",
  "Create a developer onboarding guide with access steps, first ticket, docs, and mentor owner.",
  "Design an environment comparison view with versions, config drift, and deploy eligibility.",
  "Build a webhook delivery debugger with failed attempts, payload preview, and replay controls.",
  "Create a schema explorer with tables, columns, samples, and access request action.",
  "Design a package release checklist with changelog, semver risk, tests, and publish approval.",
  "Create a brand campaign brief editor with audience, message pillars, channels, and approval state.",
  "Design a social media post calendar with drafts, owners, scheduled slots, and asset links.",
  "Build an ad creative review room with variants, comments, usage rights, and decision buttons.",
  "Create a press outreach tracker with journalist contacts, pitches, embargo notes, and next steps.",
  "Design a newsletter issue planner with sections, segments, subject lines, and send readiness.",
  "Build a landing page QA surface with copy checks, analytics tags, launch blockers, and sign-off.",
  "Create a media asset library view with filters, licenses, expiration dates, and download actions.",
  "Design a content brief generator form with search intent, angle, outline, and SEO constraints.",
  "Build a podcast episode production board with guests, recording tasks, assets, and approvals.",
  "Create a creator sponsorship tracker with deliverables, payment milestones, and brand safety notes.",
  "Design a procurement request flow with vendor details, budget impact, policy checks, and approvers.",
  "Build a contract clause review panel with risky terms, fallback language, owners, and due dates.",
  "Create an invoice exception resolver with line items, evidence, payment hold, and approval actions.",
  "Design a travel expense claim form with receipts, policy warnings, and reimbursement summary.",
  "Build a subscription change panel with current plan, next plan, usage limits, and renewal switch.",
  "Create a purchase order receiving screen with partial shipments, discrepancies, and vendor notes.",
  "Design a billing dispute case view with evidence, customer history, coverage, and resolution choices.",
  "Build a budget reallocation workflow with source category, destination category, and impact review.",
  "Create a vendor onboarding checklist with required documents, tax details, and risk rating.",
  "Design a board approval packet with agenda items, decision options, owners, and meeting materials.",
  "Build an employee onboarding journey with pre-start tasks, equipment pickup, access, and buddy info.",
  "Create a time-off approval panel with coverage conflicts, team calendar notes, and manager actions.",
  "Design a performance review writing workspace with goals, peer feedback, calibration, and draft state.",
  "Build a recruiting intake form with hiring goals, interview plan, must-have skills, and compensation range.",
  "Create an internal transfer request view with current manager, target team, rationale, and approvals.",
  "Design a compensation adjustment review with band position, rationale, effective date, and audit notes.",
  "Build a team skills matrix editor with levels, gaps, learning options, and owner assignments.",
  "Create a pulse survey follow-up planner with themes, proposed actions, owners, and deadlines.",
  "Design an interview debrief room with candidate signal, panel notes, concerns, and hiring decision.",
  "Build a manager one-on-one prep surface with topics, commitments, blockers, and next meeting plan.",
  "Create a lesson planning workspace with objectives, activities, materials, timing, and assessment.",
  "Design a classroom attendance intervention view with absent students, reasons, guardians, and actions.",
  "Build a scholarship application review panel with eligibility, scoring, essays, and decision state.",
  "Create a course module builder with lessons, quizzes, prerequisites, and publish readiness.",
  "Design a tutor session planner with student goals, prior homework, exercises, and follow-up tasks.",
  "Build a workshop facilitation checklist with room setup, materials, roles, and contingency plan.",
  "Create a certification renewal tracker with attempts, deadlines, evidence, and reminder settings.",
  "Design a student accommodation request workflow with documentation, review notes, and approvals.",
  "Build a learning path recommendation page with modules, skill gaps, time estimate, and enrollment action.",
  "Create a grading rubric editor with criteria, levels, point ranges, and feedback snippets.",
  "Design a clinic intake flow with symptoms, insurance, priority triage, and appointment options.",
  "Build a lab result review page with biomarkers, ranges, flags, patient notes, and next steps.",
  "Create a medication refill request panel with adherence, pharmacy, warnings, and clinician approval.",
  "Design a care plan checklist with tasks, responsible roles, due dates, and progress status.",
  "Build a telehealth visit summary with diagnosis notes, prescriptions, referrals, and follow-ups.",
  "Create a mental health check-in form with mood, stressors, support contacts, and safety plan.",
  "Design a fitness coaching plan with workouts, recovery score, nutrition notes, and adjustment slider.",
  "Build a nutrition meal planner with macro targets, grocery list, recipes, and prep schedule.",
  "Create a physical therapy session tracker with exercises, pain scale, progress, and homework.",
  "Design a patient referral coordinator with specialist options, documents, availability, and booking action.",
  "Create a trip itinerary builder with cities, bookings, transport choices, and travel warnings.",
  "Design a flight disruption assistant with passenger impact, rebooking options, vouchers, and notifications.",
  "Build a hotel front desk panel with arrivals, room readiness, guest notes, and issue escalation.",
  "Create a restaurant reservation manager with tables, waitlist, dietary notes, and seating action.",
  "Design a concierge request workspace with guest preferences, vendor options, and service recovery.",
  "Build a venue setup schedule with rooms, vendors, equipment, and day-of checklist.",
  "Create a tour booking flow with availability, guests, add-ons, waiver status, and payment details.",
  "Design a property maintenance request panel with photos, priority, vendor assignment, and status.",
  "Build a travel packing assistant with weather, itinerary needs, luggage limits, and checklist progress.",
  "Create a museum visit planner with exhibit zones, accessibility needs, tickets, and recommended route.",
  "Design a product detail editor with variants, inventory, images, SEO fields, and publish checks.",
  "Build a returns authorization workflow with reason codes, condition notes, refund method, and fraud signals.",
  "Create a price change approval panel with margin impact, competitor references, and effective date.",
  "Design a merchandising collection planner with products, promotions, stock risk, and launch tasks.",
  "Build a seller payout setup checklist with identity checks, bank details, tax forms, and status.",
  "Create a loyalty reward rule editor with tiers, earning rules, exclusions, and preview.",
  "Design a review moderation queue with flagged text, sentiment, policy reason, and response action.",
  "Build a product bundle composer with included items, discount logic, availability, and validation alerts.",
  "Create a store pickup coordinator with orders, staging location, customer arrival, and handoff state.",
  "Design a gift card support case view with balance history, fraud notes, and resolution actions.",
  "Build an access audit review with risky permissions, inactive users, owners, and revoke actions.",
  "Create a phishing report triage panel with sender, headers, indicators, and containment steps.",
  "Design a privacy request workflow with identity verification, data scope, due date, and export status.",
  "Build a policy exception approval page with rationale, compensating controls, expiry, and approver notes.",
  "Create a vendor security questionnaire review with control gaps, evidence links, and risk score.",
  "Design an audit evidence collection surface with controls, documents, owners, and missing proof.",
  "Build a risk register editor with probability, impact, mitigations, owner, and review cadence.",
  "Create a security incident timeline with events, indicators, containment actions, and communication notes.",
  "Design a secrets exposure response flow with affected systems, rotation steps, and verification.",
  "Build a compliance training assignment panel with audience, due date, exceptions, and reminder switch.",
  "Create a dataset catalog page with lineage, owner, sensitivity, sample fields, and access request.",
  "Design a report builder with dimensions, filters, preview rows, and export options.",
  "Build a data labeling task queue with instructions, quality score, reviewer notes, and submit action.",
  "Create a data contract review workflow with producers, consumers, schema changes, and approval state.",
  "Design a research study intake form with hypothesis, cohort, metrics, risks, and review board notes.",
  "Build an experiment decision page with variants, evidence, guardrails, and ship-or-stop action.",
  "Create a metrics definition registry entry with formula, owner, caveats, and downstream usage.",
  "Design a data access request form with purpose, duration, sensitivity, and approver routing.",
  "Build a backup restore drill checklist with target system, restore point, validation, and sign-off.",
  "Create a survey analysis workspace with respondent segments, notable quotes, themes, and action plan.",
  "Design a personal weekly planning board with focus blocks, priorities, chores, and reflection.",
  "Build a reading list manager with books, notes, priority, reading progress, and next pick.",
  "Create a job search tracker with applications, contacts, interview prep, and follow-up dates.",
  "Design a household maintenance checklist with rooms, recurring tasks, costs, and service providers.",
  "Build a family schedule board with events, pickups, chores, reminders, and conflict alerts.",
  "Create a decision journal entry with options, criteria, confidence, outcome date, and revisit reminder.",
  "Design a personal finance budget planner with bills, savings goals, spending limits, and warnings.",
  "Build a habit reflection surface with streaks, blockers, mood notes, and next commitment.",
  "Create a meal prep planner with recipes, grocery groups, cooking order, and storage notes.",
  "Design a home automation scene editor with room switches, temperature slider, security state, and schedule.",
  "Build an editorial assignment board with article ideas, writers, stages, deadlines, and reviewer notes.",
  "Create a screenplay scene organizer with characters, locations, beats, continuity notes, and revision action.",
  "Design a video production shot list with locations, equipment, talent, timing, and approval status.",
  "Build a photography client proofing flow with selects, retouch notes, usage rights, and invoice link.",
  "Create a music release planner with tracks, artwork, distribution checklist, and promotion tasks.",
  "Design a live stream control checklist with scenes, moderators, sponsor reads, and emergency fallback.",
  "Build a design critique board with frames, comments, severity, owners, and resolution status.",
  "Create a translation review workspace with source text, target variants, glossary notes, and approval.",
  "Design a book launch campaign planner with reviewers, events, assets, and milestone progress.",
  "Build a comic issue production tracker with script, pencils, inks, lettering, and print handoff.",
  "Create a guild raid roster planner with roles, attendance, loot notes, and ready check.",
  "Design a tabletop RPG session prep surface with scenes, NPCs, clues, maps, and pacing.",
  "Build a game patch notes editor with balance changes, known issues, assets, and publish approval.",
  "Create a tournament bracket admin with player check-in, match results, disputes, and stream schedule.",
  "Design a player support appeal review with ban reason, evidence, history, and decision actions.",
  "Build a game economy tuning panel with item prices, drop rates, warnings, and rollout controls.",
  "Create a community event signup flow with teams, roles, rules acceptance, and reminders.",
  "Design a quest authoring tool with objectives, rewards, prerequisites, and localization notes.",
  "Build a beta tester feedback room with devices, bug categories, repro notes, and severity choice.",
  "Create a game accessibility review checklist with settings, blockers, test notes, and owner actions.",
  "Design a grant application review panel with eligibility, budget, impact story, and scoring rubric.",
  "Build a volunteer shift scheduler with roles, availability, training status, and reminder actions.",
  "Create a city service request intake flow with location, category, photos, and routing.",
  "Design a public meeting agenda builder with speakers, time boxes, documents, and vote items.",
  "Build a donation thank-you workflow with donor segment, message preview, and follow-up tasks.",
  "Create a disaster relief supply coordinator with needs, locations, transport, and urgency.",
  "Design a community garden plot manager with applicants, assignments, rules, and seasonal tasks.",
  "Build a library hold request panel with patron info, item availability, pickup branch, and alerts.",
  "Create a nonprofit program outcome report with activities, participant notes, evidence, and next actions.",
  "Design a citizen feedback moderation queue with topics, sentiment, duplicates, and response owner.",
  "Build a fleet maintenance planner with vehicles, service intervals, defects, and mechanic assignment.",
  "Create a field inspection form with site conditions, photos checklist, findings, and sign-off.",
  "Design a warehouse pick-pack flow with order batches, substitutions, packing notes, and exceptions.",
  "Build a delivery route adjustment panel with stops, delays, driver notes, and customer notifications.",
  "Create a manufacturing batch release checklist with tests, deviations, approvals, and quarantine switch.",
  "Design an equipment checkout kiosk with item condition, borrower details, due date, and deposit status.",
  "Build a construction daily report with crews, weather, work completed, blockers, and safety notes.",
  "Create a maintenance work order board with priority, parts required, technician, and completion proof.",
  "Design a farm harvest planner with fields, crews, equipment, storage, and quality checks.",
  "Build a lab sample chain-of-custody surface with transfers, storage conditions, tests, and alerts.",
  "Create a museum exhibit installation tracker with artifacts, conservation notes, crates, and curators.",
  "Design an archeology dig log with trench details, finds, photos, catalog IDs, and next actions.",
  "Build a clinical trial visit coordinator with participants, procedures, deviations, and document status.",
  "Create a space mission anomaly review panel with subsystem telemetry, hypotheses, and command approval.",
  "Design an observatory night plan with targets, weather windows, instruments, and priority changes.",
  "Build a chemistry inventory request flow with hazards, storage, quantities, and approval routing.",
  "Create a research paper submission checklist with authors, figures, ethics, and journal requirements.",
  "Design a specimen collection planner with sites, permits, containers, and preservation notes.",
  "Build a grant budget justification editor with categories, assumptions, reviewers, and compliance checks.",
  "Create a conference poster review workspace with sections, figures, accessibility, and print readiness.",
  "Design a real estate showing scheduler with clients, properties, time windows, and feedback capture.",
  "Build a tenant move-in checklist with deposits, keys, inspections, utilities, and welcome packet.",
  "Create a construction change order workflow with scope, cost impact, drawings, and approvals.",
  "Design a manufacturing quality hold review with batch data, defects, containment, and disposition.",
  "Build a facility space request form with capacity, layout needs, equipment, and approval notes.",
  "Create an insurance claim evidence review with coverage, photos, documents, adjuster notes, and decision.",
  "Design a loan application underwriting panel with documents, ratios, conditions, and approval state.",
  "Build a legal matter timeline with filings, deadlines, parties, documents, and next hearing.",
  "Create an architecture materials selection board with samples, costs, sustainability notes, and decision.",
  "Design a repair estimate approval flow with parts, labor, warranty, customer consent, and payment.",
  "Build a support ticket reply composer with customer context, sentiment, macros, and policy warnings.",
  "Create an account onboarding workspace with milestones, blockers, contacts, and kickoff notes.",
  "Design a renewal negotiation prep panel with usage, stakeholders, risks, and concession options.",
  "Build a customer training session planner with agenda, attendees, exercises, and follow-up tasks.",
  "Create a bug reproduction intake form with environment, steps, expected result, and attachments checklist.",
  "Design a refund review flow with order history, policy rules, fraud notes, and customer message.",
  "Build a churn rescue playbook with reasons, save offers, owner assignment, and next contact.",
  "Create an implementation handoff form with scope, integrations, risks, and launch date.",
  "Design a customer advisory board agenda with participants, topics, feedback capture, and action items.",
  "Build a service recovery case view with guest issue, compensation options, staff owner, and follow-up.",
  "Create a command palette configuration panel with actions, shortcuts, permissions, and preview.",
  "Design a settings center with grouped preferences, search, toggles, and save review.",
  "Build a workspace switcher shell with recent projects, teams, notifications, and quick actions.",
  "Create a mobile app permission onboarding flow with benefits, privacy notes, and skip paths.",
  "Design a calendar rescheduling assistant with conflicts, attendee priorities, and suggested slots.",
  "Build a visual rule builder with conditions, operators, validation, and test cases.",
  "Create a notification preference center with channels, quiet hours, topic subscriptions, and preview.",
  "Design a file import wizard with mapping, validation errors, duplicates, and commit step.",
  "Build a role-based access editor with users, groups, inherited permissions, and change summary.",
  "Create a launch control room with checklist, owners, timeline, alerts, and final go/no-go action.",
  "Design a generative dashboard composer with layout suggestions, data bindings, tone controls, and live preview.",
  "Build an interface remix studio with source screen upload, component swaps, style constraints, and compare modes.",
  "Create a product onboarding story builder with chapters, checkpoints, personalization fields, and completion analytics.",
  "Design a multi-agent mission planner with specialist lanes, handoff cards, shared context, and escalation controls.",
  "Build a scenario simulator control panel with assumptions, timeline branches, outcome metrics, and replay actions.",
  "Create a design system coverage auditor with component usage, token gaps, accessibility flags, and migration tasks.",
  "Design a spatial workspace map with zones, pinned artifacts, collaborator presence, and focus mode controls.",
  "Build a launch narrative generator with audience segments, proof points, objections, and approved message variants.",
  "Create a founder investor update composer with metrics, asks, risks, wins, and board-ready export.",
  "Design a startup runway command center with burn scenarios, hiring toggles, revenue inputs, and survival milestones.",
  "Build a creator storefront builder with collections, drops, waitlist modules, and conversion diagnostics.",
  "Create a luxury service booking concierge with preferences, availability, add-ons, and white-glove confirmation.",
  "Design a smart contract deployment review with network choice, audits, permissions, and final signature checklist.",
  "Build a token launch operations room with eligibility, vesting table, compliance notes, and communications calendar.",
  "Create a multiplayer moderation cockpit with live reports, context snippets, sanctions, and appeal tracking.",
  "Design a creator community health dashboard with member cohorts, engagement rituals, risks, and intervention plans.",
  "Build a conference matchmaking app with attendee goals, meeting slots, topic tags, and intro message drafts.",
  "Create an immersive exhibit control desk with room states, media cues, accessibility routes, and incident notes.",
  "Design a digital twin facility panel with floor assets, sensor status, maintenance predictions, and override actions.",
  "Build an autonomous fleet dispatcher with route confidence, weather risks, depot capacity, and exception queue.",
  "Create a crisis communications war room with statements, stakeholder lists, approval chain, and sentiment timeline.",
  "Design a newsroom breaking story desk with sources, verification status, publish windows, and legal review.",
  "Build a documentary research archive with interview clips, evidence threads, release rights, and edit markers.",
  "Create a visual bookmarking moodboard with saved pages, tags, color extraction, notes, and presentation layout.",
  "Design a personal knowledge graph editor with entities, relationships, source confidence, and review reminders.",
  "Build a memory palace study planner with rooms, concepts, recall drills, and spaced repetition schedule.",
  "Create a deep work session dashboard with goals, distractions, energy level, and end-of-block reflection.",
  "Design a life admin command center with renewals, documents, appointments, and priority triage.",
  "Build a relocation planning hub with neighborhoods, lease tasks, movers, budget, and decision matrix.",
  "Create a wedding weekend operations board with vendors, timelines, guest needs, and contingency plans.",
  "Design a boutique hotel guest journey with arrival cues, preference cards, service moments, and recovery actions.",
  "Build a tasting menu planning surface with courses, dietary constraints, wine pairings, and prep timing.",
  "Create a chef inventory improvisation tool with available ingredients, substitutions, menus, and cost guardrails.",
  "Design a fashion capsule wardrobe planner with looks, occasions, garment care, and packing lists.",
  "Build a custom furniture quote builder with materials, dimensions, finish options, and delivery milestones.",
  "Create an interior styling board with room zones, product options, budget splits, and approval notes.",
  "Design a real-time event production console with cues, speakers, stage assets, and incident escalation.",
  "Build a sponsor activation planner with inventory, audience fit, deliverables, and proof-of-performance metrics.",
  "Create a fan engagement quest board with challenges, rewards, leaderboard, and moderation checkpoints.",
  "Design a streaming show rundown with segments, graphics, guests, chat prompts, and timing warnings.",
  "Build a tabletop campaign wiki editor with factions, locations, secrets, session notes, and reveal controls.",
  "Create a puzzle hunt control panel with teams, hint requests, unlocks, and live difficulty adjustments.",
  "Design a game narrative branching editor with scenes, choices, consequences, localization, and continuity checks.",
  "Build a level design review surface with playtest notes, heatmaps, issue severity, and iteration tasks.",
  "Create an esports team practice planner with scrim blocks, map focus, player goals, and review clips.",
  "Design a wellness retreat planner with sessions, facilitator needs, guest preferences, and capacity warnings.",
  "Build a meditation app personalization flow with goals, time windows, guidance style, and progress reflection.",
  "Create a sleep coaching dashboard with routines, environment factors, trends, and experiment suggestions.",
  "Design a remote care caregiver portal with daily notes, medication checks, appointments, and alert thresholds.",
  "Build a fertility clinic journey tracker with milestones, lab dates, medications, and clinician messages.",
  "Create a clinical operations bed board with patient flow, staffing pressure, transfers, and discharge blockers.",
  "Build a civic participatory budgeting portal with proposals, district impact, cost ranges, and voting status.",
  "Create a local newsletter newsroom with story leads, neighborhood beats, sponsor slots, and publishing cadence.",
  "Design a public transit disruption panel with affected lines, replacement options, crowding, and rider alerts.",
  "Build a city permit precheck wizard with property details, documents, fees, and inspector routing.",
  "Create a climate adaptation project tracker with hazards, interventions, funding, and resilience metrics.",
  "Design a carbon accounting workspace with scopes, emission factors, evidence, and reduction initiatives.",
  "Build a renewable energy site assessment with parcels, grid proximity, permits, and financial model inputs.",
  "Create an electric vehicle charger operations dashboard with uptime, queues, pricing, and maintenance tickets.",
  "Design a supply chain resilience map with suppliers, lanes, disruption signals, and alternate sourcing.",
  "Build a customs clearance desk with shipment documents, duty estimates, holds, and broker messages.",
  "Create a port operations berth planner with vessels, cranes, labor windows, and congestion warnings.",
  "Design an airline crew recovery workspace with legality checks, hotels, deadheads, and passenger impact.",
  "Create an industrial safety observation app with hazards, corrective actions, responsible crews, and verification.",
  "Design a quality inspection tablet flow with sample plans, defect photos, measurements, and disposition.",
  "Build a packaging artwork approval panel with dielines, claims, translations, and print readiness.",
  "Create a pharmaceutical batch genealogy viewer with lots, tests, deviations, and release dependencies.",
  "Design a legal e-discovery review room with custodians, document clusters, privilege flags, and export queue.",
  "Create a wealth planning scenario workspace with goals, accounts, tax assumptions, and trade-off charts.",
  "Design a private banking relationship dashboard with family entities, mandates, next actions, and risk notes.",
  "Build an insurance product configurator with coverage modules, exclusions, premium preview, and compliance checks.",
  "Create a fraud investigation graph with entities, transactions, device signals, and case decisions.",
  "Design a treasury liquidity command center with balances, forecasts, approvals, and transfer limits.",
  "Build a marketplace seller quality dashboard with defects, disputes, coaching tasks, and suspension risk.",
  "Create a fashion drop allocation tool with demand forecast, region splits, VIP access, and restock rules.",
  "Build a customer sentiment synthesis room with calls, tickets, themes, quote cards, and roadmap links.",
  "Create a voice-of-customer prioritization board with pain points, segments, revenue impact, and owners.",
  "Design a B2B product discovery canvas with jobs, objections, workflows, evidence, and experiment backlog.",
  "Build a feature request deduplication interface with clusters, customer logos, ARR impact, and status updates.",
  "Create a product telemetry anomaly triage surface with cohorts, events, releases, and rollback hints.",
  "Design a growth experiment factory with hypotheses, audiences, creative variants, and learning archive.",
  "Build a pricing packaging workbench with plans, entitlements, guardrails, and customer examples.",
  "Create a sales deal desk with discount tiers, legal terms, implementation effort, and approval chain.",
  "Design a partner portal onboarding hub with credentials, certification steps, co-sell leads, and readiness score.",
  "Build a customer success renewal room with health signals, adoption gaps, stakeholders, and mutual action plan.",
  "Create an enterprise implementation control tower with phases, dependencies, risks, and executive updates.",
  "Design a support escalation command center with severity, timeline, engineering owners, and customer comms.",
  "Build a documentation freshness auditor with pages, owners, stale sections, traffic, and rewrite queue.",
  "Create an API playground onboarding flow with sample requests, auth state, logs, and generated snippets.",
  "Design a developer portal home with SDK cards, changelog, incidents, keys, and quickstart progress.",
  "Build a cloud cost optimization cockpit with services, rightsizing options, commitments, and savings approvals.",
  "Create an infrastructure capacity planner with regions, quotas, demand forecast, and expansion tasks.",
  "Design an observability alert tuning desk with noisy rules, thresholds, recent incidents, and test mode.",
  "Build a data pipeline backfill console with partitions, dependencies, validation, and pause controls.",
  "Create a privacy-safe analytics builder with permitted fields, aggregation rules, consent checks, and preview.",
  "Design an AI model evaluation arena with task sets, judge rubrics, side-by-side outputs, and promotion gates.",
  "Build an agent tool permission sandbox with simulated calls, data exposure labels, denials, and audit trail.",
  "Create a synthetic data generation studio with schemas, constraints, distributions, and privacy risk report.",
  "Design a no-code internal tool builder with data sources, component palette, permissions, and publish review.",
  "Build an adaptive accessibility settings panel with contrast preview, motion controls, captions, and saved profiles.",
] as const;

export function pickRandomStarterPrompts(
  count = 3,
  random: () => number = Math.random,
) {
  const prompts = [...POPULAR_STARTER_PROMPTS];

  for (let index = prompts.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1));
    [prompts[index], prompts[swapIndex]] = [prompts[swapIndex], prompts[index]];
  }

  return prompts.slice(0, count);
}
